
export const POPULAR_MOVIES_FETCH_REQUEST = 'POPULAR_MOVIES_FETCH_REQUEST';
export const POPULAR_MOVIES_FETCH_SUCCESS = 'POPULAR_MOVIES_FETCH_SUCCESS';
export const POPULAR_MOVIES_FETCH_FAIL = 'POPULAR_MOVIES_FETCH_FAIL';

export const TOPRATED_MOVIES_FETCH_REQUEST = 'TOPRATED_MOVIES_FETCH_REQUEST';
export const TOPRATED_MOVIES_FETCH_SUCCESS = 'TOPRATED_MOVIES_FETCH_SUCCESS';
export const TOPRATED_MOVIES_FETCH_FAIL = 'TOPRATED_MOVIES_FETCH_FAIL';

export const UPCOMING_MOVIES_FETCH_REQUEST = 'UPCOMING_MOVIES_FETCH_REQUEST';
export const UPCOMING_MOVIES_FETCH_SUCCESS = 'UPCOMING_MOVIES_FETCH_SUCCESS';
export const UPCOMING_MOVIES_FETCH_FAIL = 'UPCOMING_MOVIES_FETCH_FAIL';

export const SEARCH_MOVIES_REQUEST = 'SEARCH_MOVIES_REQUEST';
export const SEARCH_MOVIES_SUCCESS = 'SEARCH_MOVIES_SUCCESS';
export const SEARCH_MOVIES_CANCEL = 'SEARCH_MOVIES_CANCEL';
export const SEARCH_MOVIES_FAIL = 'SEARCH_MOVIES_FAIL';

export const USER_VISITED_MOVIE = 'USER_VISITED_MOVIE';

export const ADD_ERROR = 'ADD_ERROR';
export const DELETE_ERROR = 'DELETE_ERROR';